# Generated by Django 5.0.6 on 2024-06-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialTrade',
            fields=[
                ('trade_date', models.DateTimeField()),
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('security_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=30)),
                ('comment', models.CharField(blank=True, max_length=150)),
                ('strategy', models.CharField(max_length=50)),
                ('strategy_id', models.CharField(max_length=100)),
                ('instrument_type', models.CharField(choices=[('bond', 'Bond'), ('cds', 'CDS'), ('futures', 'Futures'), ('fx', 'FX')], editable=False, max_length=10)),
                ('price', models.FloatField()),
                ('spread', models.FloatField()),
                ('notional', models.FloatField()),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('no_of_contracts', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_date', models.DateTimeField()),
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('security_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=30)),
                ('comment', models.CharField(blank=True, max_length=150)),
                ('strategy', models.CharField(max_length=50)),
                ('strategy_id', models.CharField(max_length=100)),
                ('instrument_type', models.CharField(choices=[('bond', 'Bond'), ('cds', 'CDS'), ('futures', 'Futures'), ('fx', 'FX')], editable=False, max_length=10)),
                ('price', models.FloatField()),
                ('spread', models.FloatField()),
                ('notional', models.FloatField()),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('no_of_contracts', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
