# Generated by Django 5.0.6 on 2024-06-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialTrade',
            fields=[
                ('trade_date', models.DateTimeField()),
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('security_id', models.CharField(max_length=100)),
                ('username', models.CharField(editable=False, max_length=150)),
                ('comment', models.CharField(blank=True, max_length=150)),
                ('strategy', models.CharField(blank=True, choices=[('active_short', 'Active Short'), ('relval', 'RelVal'), ('slbs', 'SLBs'), ('curves', 'Curves'), ('use_of_proceeds', 'Use of Proceeds'), ('hedge', 'Hedge')], max_length=15, null=True)),
                ('strategy_id', models.CharField(max_length=100)),
                ('instrument_type', models.CharField(choices=[('bond', 'Bond'), ('cds', 'CDS'), ('futures', 'Futures'), ('fx', 'FX')], editable=False, max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
                ('spread', models.DecimalField(blank=True, decimal_places=13, max_digits=20, null=True)),
                ('notional', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
                ('direction', models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4, null=True)),
                ('no_of_contracts', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_date', models.DateTimeField()),
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('security_id', models.CharField(max_length=100)),
                ('username', models.CharField(editable=False, max_length=150)),
                ('comment', models.CharField(blank=True, max_length=150)),
                ('strategy', models.CharField(blank=True, choices=[('active_short', 'Active Short'), ('relval', 'RelVal'), ('slbs', 'SLBs'), ('curves', 'Curves'), ('use_of_proceeds', 'Use of Proceeds'), ('hedge', 'Hedge')], max_length=15, null=True)),
                ('strategy_id', models.CharField(max_length=100)),
                ('instrument_type', models.CharField(choices=[('bond', 'Bond'), ('cds', 'CDS'), ('futures', 'Futures'), ('fx', 'FX')], editable=False, max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
                ('spread', models.DecimalField(blank=True, decimal_places=13, max_digits=20, null=True)),
                ('notional', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
                ('direction', models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4, null=True)),
                ('no_of_contracts', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
