# Generated by Django 5.0.6 on 2024-06-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialtrade',
            name='direction',
            field=models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4),
        ),
        migrations.AlterField(
            model_name='potentialtrade',
            name='no_of_contracts',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='potentialtrade',
            name='notional',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='potentialtrade',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='potentialtrade',
            name='spread',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='direction',
            field=models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4),
        ),
        migrations.AlterField(
            model_name='trade',
            name='no_of_contracts',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='notional',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='spread',
            field=models.FloatField(blank=True),
        ),
    ]
