# Generated by Django 5.0.6 on 2024-06-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_alter_potentialtrade_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialtrade',
            name='strategy',
            field=models.CharField(choices=[('active_short', 'Active Short'), ('relval', 'RelVal'), ('slbs', 'SLBs'), ('curves', 'Curves'), ('use_of_proceeds', 'Use of Proceeds'), ('hedge', 'Hedge')], max_length=15),
        ),
        migrations.AlterField(
            model_name='trade',
            name='strategy',
            field=models.CharField(choices=[('active_short', 'Active Short'), ('relval', 'RelVal'), ('slbs', 'SLBs'), ('curves', 'Curves'), ('use_of_proceeds', 'Use of Proceeds'), ('hedge', 'Hedge')], max_length=15),
        ),
    ]
