# Generated by Django 5.0.6 on 2024-06-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_alter_potentialtrade_strategy_alter_trade_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialtrade',
            name='strategy',
            field=models.CharField(blank=True, choices=[('active_short', 'Active Short'), ('relval', 'RelVal'), ('slbs', 'SLBs'), ('curves', 'Curves'), ('use_of_proceeds', 'Use of Proceeds'), ('hedge', 'Hedge')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='potentialtrade',
            name='username',
            field=models.CharField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='trade',
            name='strategy',
            field=models.CharField(blank=True, choices=[('active_short', 'Active Short'), ('relval', 'RelVal'), ('slbs', 'SLBs'), ('curves', 'Curves'), ('use_of_proceeds', 'Use of Proceeds'), ('hedge', 'Hedge')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='username',
            field=models.CharField(editable=False, max_length=150),
        ),
    ]
