# Generated by Django 5.0.6 on 2024-06-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_alter_potentialtrade_strategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialtrade',
            name='notional',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='potentialtrade',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='potentialtrade',
            name='spread',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='notional',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='spread',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=20, null=True),
        ),
    ]
